# Generated by Django 4.2.18 on 2025-02-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="profiles/")),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("skills", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "fitment_analysis",
                    models.CharField(
                        choices=[
                            ("good", "Good Fit"),
                            ("maybe", "Maybe"),
                            ("bad", "Bad Fit"),
                        ],
                        default="maybe",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interviewer_name", models.CharField(max_length=255)),
                (
                    "score",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ],
                        default=0,
                    ),
                ),
                (
                    "fitment",
                    models.CharField(
                        choices=[
                            ("good", "Good Fit"),
                            ("maybe", "Maybe"),
                            ("bad", "Bad Fit"),
                        ],
                        default="maybe",
                        max_length=20,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("selected", "Selected"),
                            ("rejected", "Rejected"),
                            ("shortlist", "Shortlist"),
                            ("forward", "Forward to next round"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("comments", models.TextField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
    ]
