# Generated by Django 4.2.18 on 2025-02-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewfeedback",
            name="interviewed_for_team",
            field=models.CharField(
                blank=True,
                choices=[
                    ("backend", "Django Backend"),
                    ("frontend", "Vue Frontend"),
                    ("nodejs", "Node JS"),
                    ("cloud", "Cloud"),
                    ("qa", "Quality"),
                    ("implementtion", "Implementation"),
                    ("automation", "Automation"),
                    ("machine_learning", "Deep Tech"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
