# Generated by Django 4.2.18 on 2025-02-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_interviewfeedback_interviewed_for_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="interview_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="interview_scheduled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_contacted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_for_team",
            field=models.CharField(
                blank=True,
                choices=[
                    ("backend", "Django Backend"),
                    ("frontend", "Vue Frontend"),
                    ("nodejs", "Node JS"),
                    ("cloud", "Cloud"),
                    ("qa", "Quality"),
                    ("implementtion", "Implementation"),
                    ("automation", "Automation"),
                    ("machine_learning", "Deep Tech"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
